version: '3'

networks:
  nginx_net:
    external:
      name: nginx_net

volumes:
  pg_data: { }

services:
  flask:
    container_name: "fb_web"
    image: python:3.9-buster
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
    command: python3 run.py
    restart: unless-stopped
    build: .
    networks:
      - nginx_net